import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import { TopNav } from "@/components/top-nav";
import { SideNav } from "@/components/side-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen bg-background">
      <SideNav>
        <main className="flex-1 overflow-auto">
          <TopNav />
          {children}
        </main>
      </SideNav>
      <Toaster />
    </div>
  );
}
